# Generated by Django 5.1.5 on 2025-01-24 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('max_tasks', models.IntegerField()),
                ('tasks_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('priority', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'pending'), (2, 'in_progress'), (3, 'completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='main.worker')),
            ],
        ),
    ]
